#requires -Version 7
<#
    Generates NiceEntry/Icons/MaterialIcon.cs from the Material Design Icons
    webfont _variables.scss (icon name -> codepoint map).

    Run this ONLY when intentionally bumping the MDI version -- never automatically.
    The URL is pinned to a concrete tag so re-runs are reproducible; bumping means
    editing $MdiVersion here AND re-downloading the matching .ttf (Task 2, Step 2).
#>
param(
    [string]$MdiVersion = "v7.4.47",
    [string]$ScssUrl    = "https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/$MdiVersion/scss/_variables.scss",
    [string]$OutputPath = "$PSScriptRoot/../NiceEntry/Icons/MaterialIcon.cs"
)

$ErrorActionPreference = "Stop"

$scss = (Invoke-WebRequest -Uri $ScssUrl -UseBasicParsing).Content

# Matches entries like:  "ab-testing": F01C9,
$regex   = [regex]'"(?<name>[a-z0-9-]+)"\s*:\s*(?<code>[0-9A-Fa-f]{4,6})'
$entries = $regex.Matches($scss)
if ($entries.Count -eq 0) { throw "No icon entries parsed from $ScssUrl" }

$textInfo = (Get-Culture).TextInfo
$seen     = [System.Collections.Generic.HashSet[string]]::new()
$sb       = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine("// <auto-generated />")
[void]$sb.AppendLine("// Generated from Material Design Icons webfont (scss/_variables.scss).")
[void]$sb.AppendLine("// Do not edit by hand. Regenerate with tools/Generate-MaterialIcon.ps1.")
[void]$sb.AppendLine()
[void]$sb.AppendLine("namespace NiceEntry;")
[void]$sb.AppendLine()
[void]$sb.AppendLine("/// <summary>Material Design Icons glyphs. The enum value is the font codepoint.</summary>")
[void]$sb.AppendLine("public enum MaterialIcon")
[void]$sb.AppendLine("{")

foreach ($m in $entries) {
    $name = $m.Groups['name'].Value
    $code = $m.Groups['code'].Value

    # kebab-case -> PascalCase, keeping numeric segments as-is
    $pascal = ($name -split '-' | ForEach-Object {
        if ($_ -match '^\d') { $_ } else { $textInfo.ToTitleCase($_) }
    }) -join ''

    # C# identifiers cannot start with a digit
    if ($pascal -match '^\d') { $pascal = "_$pascal" }

    if (-not $seen.Add($pascal)) { continue }  # defensive de-dupe

    [void]$sb.AppendLine("    $pascal = 0x$code,")
}

[void]$sb.AppendLine("}")

$dir = Split-Path -Parent $OutputPath
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString())
Write-Host "Wrote $($seen.Count) icons to $OutputPath"
